#!/bin/sh

version=$(git rev-parse --short HEAD)

if [ -f .commit ]
    then
    rm .commit

    echo 'Version = { id: version };' | sed "s/version/\'${version}\'/g" > js/version.js
    git add js/version.js
    git commit -m "Bump up version" --no-verify
fi
